language: cpp
script: cd cpp && make
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
    env:
    - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
  - os: linux
    compiler:
    - clang
before_install:
- eval "${MATRIX_EVAL}"
