language: cpp
os: linux
dist: trusty
script: cd cpp && make
matrix:
  include:
  - compiler:
    - g++
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
    env:
    - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    before_install:
    - eval "${MATRIX_EVAL}"
  - compiler:
    - clang
