language: cpp
os: linux
dist: trusty
script: cd cpp && make
matrix:
  include:
  - compiler:
    - g++
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
    before_install:
    - eval "CXX=g++-6"
  - compiler:
    - clang
